### ISSUE TITLE
FontForge not installed properly! Please install FontForge with Python scripting support first.

### ISSUE THREAD

**Issue by iammrhappy** [dtinth/YosemiteSystemFontPatcher#17]
I keep on getting this pop up when I enter the code "mkdir -p /tmp/YosemiteSystemFontPatcher && cd /tmp/YosemiteSystemFontPatcher && curl -L https://github.com/dtinth/YosemiteSystemFontPatcher/archive/master.tar.gz | tar xvz --strip 1 && ./bin/convenient-script && open ."

I followed the step by step. 
I entered "brew install fontforge --with-python" and I get "Warning: fontforge-20141126 already installed"

I'm not sure what to do at this point. 
I've tried
 brew uninstall fontforge
brew uninstall python
brew install fontforge --with-python
and it still gives me the same issue. 

Best.

Mr. Happy

**Comment by kaiyulee** [comment]
I got the same problem!

**Comment by Pyxie** [comment]
Same here.  I take it there's not a fix for this yet?

**Comment by kmj2318** [comment]
Having this same problem. All I want to do is convert Myriad Set Pro.

**Comment by sulaiman7** [comment]
Same here, I would like to install Avenir Next, I'm unable to convert the fonts into system because of that error. It seems that the author of this patch had abandoned the project, since there was no updates when he released the previous patch.

Still waiting to hear back from the author of this repo.

**Comment by dtinth** [comment]
The convenient script doesn't say much when things go wrong. Maybe you have to try to follow the manual instructions first, so that it tells you what went wrong.

What is the error output when you run this command?

```bash
python -c 'import fontforge; print "FontForge works in Python"'
```

**Comment by sulaiman7** [comment]
@dtinth I'm getting this error:
![screen shot 2015-05-27 at 12 40 35 pm](https://cloud.githubusercontent.com/assets/1150340/7829552/bfaa3044-046d-11e5-8024-ea0df1ca3c51.png)

Even I tried to convert the fonts manually using terminal the same error shows up as the screenshot.

**Comment by sulaiman7** [comment]
Would you mind sending the Avenir Next font please?

**Comment by sulaiman7** [comment]
Any update?...

**Comment by sulaiman7** [comment]
@dtinth I would like to know is it possible to fix this issue? I'm still stuck with the above error when I tried to re-install the fontforge...

**Comment by dtinth** [comment]
Could you tell me `which python` is being used? Run that in the terminal, you should see something like this:

```
▹ which python
/usr/local/bin/python
```

It should say `/usr/local/bin/python`. If it says `/usr/bin/python` then it's using the wrong one. First, try to locate the python installed by Homebrew:

```
/usr/local/bin/python -c 'print "ok"'
```

If it says `ok`, then Homebrew's Python is properly installed. Then export the PATH to that Python:

```
export PATH="/usr/local/bin:$PATH"
```

Then please try running the script again.

**Comment by sulaiman7** [comment]
Here is the complete result i re-install and follow up your commands:
```
Alpha:~ Sulaiman$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1
==> The following directories will be made group writable:
/usr/local/share/man/man8

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/share/man/man8
Password:
==> Downloading and installing Homebrew...
remote: Counting objects: 3600, done.
remote: Compressing objects: 100% (3444/3444), done.
remote: Total 3600 (delta 34), reused 1443 (delta 19), pack-reused 0
Receiving objects: 100% (3600/3600), 2.77 MiB | 188.00 KiB/s, done.
Resolving deltas: 100% (34/34), done.
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
HEAD is now at a4b216c botan: update 1.10.9 bottle.
==> Installation successful!
==> Next steps
Run `brew help` to get started
Alpha:~ Sulaiman$ brew help
Example usage:
  brew [info | home | options ] [FORMULA...]
  brew install FORMULA...
  brew uninstall FORMULA...
  brew search [foo]
  brew list [FORMULA...]
  brew update
  brew upgrade [--all | FORMULA...]
  brew pin/unpin [FORMULA...]

Troubleshooting:
  brew doctor
  brew install -vd FORMULA
  brew [--env | config]

Brewing:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]
  open https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

Further help:
  man brew
  brew home
Alpha:~ Sulaiman$ brew doctor
Your system is ready to brew.
Alpha:~ Sulaiman$ brew install fontforge --with-python
==> Installing dependencies for fontforge: libtool, gettext, libffi, glib
==> Installing fontforge dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.yosemite.bott
######################################################################## 100.0%
==> Pouring libtool-2.4.6.yosemite.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 69 files, 3.8M
==> Installing fontforge dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.4.yosemite.bot
######################################################################## 100.0%
==> Pouring gettext-0.19.4.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X provides similar software, and installing this software in
parallel can cause all kinds of trouble.

OS X provides the BSD gettext library and some software gets confused if both are in the library path.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/gettext/lib
    CPPFLAGS: -I/usr/local/opt/gettext/include

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.4: 1920 files, 21M
==> Installing fontforge dependency: libffi
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.0.13.yosemite.bott
######################################################################## 100.0%
==> Pouring libffi-3.0.13.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Some formulae require a newer version of libffi.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libffi/lib

==> Summary
🍺  /usr/local/Cellar/libffi/3.0.13: 14 files, 412K
==> Installing fontforge dependency: glib
==> Downloading https://homebrew.bintray.com/bottles/glib-2.44.1.yosemite.bottle
######################################################################## 100.0%
==> Pouring glib-2.44.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.44.1: 416 files, 18M
==> Installing fontforge dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.17.yosemite.bott
######################################################################## 100.0%
==> Pouring libpng-1.6.17.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.17: 17 files, 1.2M
==> Installing fontforge dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.5.5.yosemite.bot
######################################################################## 100.0%
==> Pouring freetype-2.5.5.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.5.5: 60 files, 2.6M
==> Installing fontforge dependency: fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.11.1.yosemite.
######################################################################## 100.0%
==> Pouring fontconfig-2.11.1.yosemite.bottle.3.tar.gz
==> /usr/local/Cellar/fontconfig/2.11.1/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.11.1: 448 files, 3.6M
==> Installing fontforge dependency: pixman
==> Downloading https://homebrew.bintray.com/bottles/pixman-0.32.6.yosemite.bott
######################################################################## 100.0%
==> Pouring pixman-0.32.6.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/pixman/0.32.6: 11 files, 1.4M
==> Installing fontforge dependency: cairo
==> Downloading https://homebrew.bintray.com/bottles/cairo-1.14.2.yosemite.bottl
######################################################################## 100.0%
==> Pouring cairo-1.14.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/cairo/1.14.2: 116 files, 6.7M
==> Installing fontforge dependency: icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-55.1.yosemite.bottle.
######################################################################## 100.0%
==> Pouring icu4c-55.1.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

OS X provides libicucore.dylib (but nothing else).

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include

==> Summary
🍺  /usr/local/Cellar/icu4c/55.1: 244 files, 66M
==> Installing fontforge dependency: harfbuzz
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-0.9.40.yosemite.bo
######################################################################## 100.0%
==> Pouring harfbuzz-0.9.40.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/harfbuzz/0.9.40: 72 files, 3.0M
==> Installing fontforge dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.28.yosemite.bo
######################################################################## 100.0%
==> Pouring pkg-config-0.28.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.28: 10 files, 612K
==> Installing fontforge dependency: gobject-introspection
==> Downloading https://homebrew.bintray.com/bottles/gobject-introspection-1.44.
######################################################################## 100.0%
==> Pouring gobject-introspection-1.44.0.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/gobject-introspection/1.44.0: 196 files, 10M
==> Installing fontforge dependency: pango
==> Downloading https://homebrew.bintray.com/bottles/pango-1.36.8.yosemite.bottl
######################################################################## 100.0%
==> Pouring pango-1.36.8.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/pango/1.36.8: 132 files, 4.8M
==> Installing fontforge dependency: zeromq
==> Downloading https://homebrew.bintray.com/bottles/zeromq-4.0.5_2.yosemite.bot
######################################################################## 100.0%
==> Pouring zeromq-4.0.5_2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/zeromq/4.0.5_2: 64 files, 2.8M
==> Installing fontforge dependency: czmq
==> Downloading https://homebrew.bintray.com/bottles/czmq-2.2.0_1.yosemite.bottl
######################################################################## 100.0%
==> Pouring czmq-2.2.0_1.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/czmq/2.2.0_1: 69 files, 1020K
==> Installing fontforge dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.yosemite.bottle.2.t
######################################################################## 100.0%
==> Pouring jpeg-8d.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/jpeg/8d: 18 files, 776K
==> Installing fontforge dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.3.yosemite.bott
######################################################################## 100.0%
==> Pouring libtiff-4.0.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.0.3: 254 files, 3.8M
==> Installing fontforge
==> Downloading https://homebrew.bintray.com/bottles/fontforge-20150430.yosemite
######################################################################## 100.0%
==> Pouring fontforge-20150430.yosemite.bottle.tar.gz
Warning: fontforge dependency gettext was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/Sulaiman/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/Sulaiman/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/fontforge/20150430: 1298 files, 35M
Alpha:~ Sulaiman$ mkdir -p /tmp/YosemiteSystemFontPatcher && cd /tmp/YosemiteSystemFontPatcher && curl -L https://github.com/dtinth/YosemiteSystemFontPatcher/archive/master.tar.gz | tar xvz --strip 1 && ./bin/convenient-script && open .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   140    0   140    0     0     70      0 --:--:--  0:00:01 --:--:--    70
100  4654  100  4654    0     0   1213      0  0:00:03  0:00:03 --:--:--  4739
x .gitignore
x README.md
x bin/
x bin/convenient-script
x bin/list-fonts
x bin/patch
2015-05-29 21:01:03.198 convenient-script[19759:949539] warning: failed to get scripting definition from /usr/bin/osascript; it may not be scriptable.
```
Please let me know how can i fix this issue? even when i did the clean installation and ran the script, still i'm getting the error as the above screenshot.

**Comment by dtinth** [comment]
Hello.

Many thanks for a detailed report. I'm quite busy now and don't have much
time to support my projects. By best guess is that it seems like installing
fontforge is not enough... You also need to install Homebrew's Python.

Please try uninstalling fontforge first, then install Python:

brew install python

Then install fontforge again.

**Comment by sulaiman7** [comment]
@dtinth Would you convert the “Avenir Next” font for me? I'm waiting for that. I can't able to get this fixed. Any solution would be greatly appreciated!

**Comment by dtinth** [comment]
Well, I think it's not legal to distribute the converted font. I saw one project that publishes such a modified font and was taken down by a DMCA notice.

**Comment by dtinth** [comment]
But yeah, this tool is quite problematic too. I also failed to run my own tool on another Mac. If I am able to fix it, then perhaps you can try again.

Another immediate solution, I guess, is to convert the font on a Linux machine. However, the convenient script will not work.

**Comment by sulaiman7** [comment]
You can share it on Dropbox and I could download it soon as before it takes
down. I guess they won't take down unless if the creator of the font had
complained to DMCA.

Kindly convert the font it's more than enough for me!

Regards,
*Sulaiman Kuthubdeen*

**Comment by sulaiman7** [comment]
I'm unable to convert it on Linux! I tried different homebrew that is
called linuxbrew. it didn't successfully convert it.

Regards,
*Sulaiman Kuthubdeen*

**Comment by sulaiman7** [comment]
Wouldn't you help to resolve this case?

Regards,
*Sulaiman Kuthubdeen*

**Comment by dtinth** [comment]
I can't get it to work on a new MacBook either, but I was able to get it to work on Ubuntu Linux. So, on Ubuntu, don't use homebrew; use its package manager.

```
sudo apt-get install fontforge python-fontforge
```

Now fontforge should work in your Linux box flawlessly.

```
python -c 'import fontforge; print "FontForge works in Python"'
```

Now you can patch your fonts, just remember to copy `HelveticaNeueDeskInterface.ttc` into the repo directory before patching:

```
bin/patch 'System Font Regular' 'FabulouslyFantasticFontName-Regular.otf'
```

Sorry for these inconvenience, but I've got a lot of ~~livin'~~other work to do.

**Comment by redkurn** [comment]
after following the suggestions from the previous guy having issues, i got it to work, but...

Unable to convert font! Error: Couldn't find a font file named /Users/x/Desktop/Bauhaus-Regular.ttf(/Users/x/Desktop/Bauhaus-Regular.ttf(Bauhaus ITC))
The requested file, Bauhaus-Regular.ttf(Bauhaus ITC)), does not exist
Traceback (most recent call last):
  File "bin/patch", line 62, in <module>
    main()
  File "bin/patch", line 15, in main
    convert(template_font, sys.argv[2])
  File "bin/patch", line 51, in convert
    source = fontforge.open(source_fontpath)
EnvironmentError: Open failed

**Comment by redkurn** [comment]
thats from my desktop, i'm going to try from the folder it created.

**Comment by redkurn** [comment]
still failed...
