### ISSUE TITLE
Segmentation Fault 11

### ISSUE THREAD

**Issue by depl0y** [dtinth/YosemiteSystemFontPatcher#18]
I have upgraded my system to 10.10.3 and I wanted to replace my font with a different one, but I have problems getting fontforge to work.

I installed homebrew, updated it and ran the fontforge install command:

`brew install fontforge --with-python`

This installs fontforge, but with the following messages:

```
==> Downloading https://homebrew.bintray.com/bottles/fontforge-20150330.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring fontforge-20150330.yosemite.bottle.tar.gz
Warning: fontforge dependency gettext was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/fontforge/20150330: 1297 files, 35M
```

Once this is done, when I try to run the python command mentioned in the readme, Python crashes with a segmentation fault 11.

I do have Xcode 6.3 installed, might that be affecting this?

**Comment by depl0y** [comment]
Building fontforge from scratch actually works:

```
brew install python gettext libpng jpeg libtiff giflib cairo pango libspiro czmq fontconfig automake libtool pkg-config glib pango 
brew install -v --debug fontforge --HEAD --with-giflib --with-x11 --with-libspiro
```

**Comment by eFiggy** [comment]
@depl0y, I tried the steps you outlined in your last post and I'm still getting the Segmentation Fault 11 error. I only have the Xcode Command Line tools installed, but it doesn't look like there were build errors or anything. Are you using Python 2 or 3?

**Comment by dtinth** [comment]
Thanks for the report.

That's very strange! Unfortunately, I just tried it on a new MacBook, and I get the same problem.

And I don't know how to fix it, so I'm converting fonts in Linux (a Vagrant box) now. :cry: :sob:

**Comment by AluminumPea** [comment]
This is how I was able to fix it on my Macbook. 

1. I removed all the mess that brew had made
2. I installed Mac Ports
3. I ran the following:

`sudo port install fontforge +python27`
`sudo port select --set python python27`

And now, it works.

**Comment by sulaiman7** [comment]
I can confirm this one works really well! Unlike on Linux and Homebrew, they're not working properly with OS X 10.10.3.

**Comment by irrg** [comment]
Working fine here. Using system python and following the directions, on 10.10.3 — Generated a new set of the “official” San Francisco fonts and they work just fine.

**Comment by hansott** [comment]
@depl0y Thanks for finding a solution. Are you sure about `--HEAD` though?

```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fontforge.rb
Error: No head is defined for fontforge
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:133:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:110:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by hansott** [comment]
https://github.com/dtinth/YosemiteAndElCapitanSystemFontPatcher/issues/18#issuecomment-92883587

The `--head` flag was removed in the formula, you can fix it by copying the contents of https://github.com/Homebrew/homebrew-core/blob/d1dfe7b506da542c8828ebd775a1f4f943e55ed7/Formula/fontforge.rb in `brew edit fontforge` and then try `brew reinstall fontforge`.

**Comment by Natee9969** [comment]
> I have upgraded my system to 10.10.3 and I wanted to replace my font with a different one, but I have problems getting fontforge to work.
> 
> I installed homebrew, updated it and ran the fontforge install command:
> 
> `brew install fontforge --with-python`
> 
> This installs fontforge, but with the following messages:
> 
> ```
> ==> Downloading https://homebrew.bintray.com/bottles/fontforge-20150330.yosemite.bottle.tar.gz
> ######################################################################## 100.0%
> ==> Pouring fontforge-20150330.yosemite.bottle.tar.gz
> Warning: fontforge dependency gettext was built with a different C++ standard
> library (libc++ from clang). This may cause problems at runtime.
> 🍺  /usr/local/Cellar/fontforge/20150330: 1297 files, 35M
> ```
> 
> Once this is done, when I try to run the python command mentioned in the readme, Python crashes with a segmentation fault 11.
> 
> I do have Xcode 6.3 installed, might that be affecting this?
